### ISSUE TITLE
TLS Kafka example

### ISSUE THREAD

**Issue by johntdyer** [dangkaka/go-kafka-avro#1]
I am having trouble figuring out how to create a TLS Kafka client using a schema registry with your library.  I am hoping you can help me w/ an example since the docs are a little bit thin in this regard.  Thanks again !

**Comment by dangkaka** [comment]
hi @johntdyer, I'm so sorry, this library is not supported LTS at this moment.
in our use case, VPN is good enough (we use AWS)
